### PR TITLE
LRQA-63181 Automate hotfix qualifier test

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-63181

### CODE REVIEW

**Comment by Kvale1733** [comment]
@kyle-miho This is what I have so far for the hotfix qualifier test. Basically I created a property that adds the qualifier to whatever module you choose and then deploys that module. I have the qualifier hard coded. Does it matter which qualifier is being added? I can make it a variable. So I can just add the property to a test and then run a smoke check. So it would be a test per module how I have it right now. I have it set to an account module just to test. Is the idea to have several tests to run for different modules that are commonly affected? So I could have one testcase that runs the same test I've included for different moduls?. Just want to know If I'm on the right track.

**Comment by Kvale1733** [comment]
@kyle-miho

**Comment by kyle-miho** [comment]
@Kvale1733 You should only need to deploy the module and check if it succesfully deploys, referencing the original bug  that had the issue encountered it on deploy, running a smoke on it will likely just make the test longer than needed and possibly more flaky. You shouldn't need to add a new property and make this change on deployment with osgi-modules-includes since this will bloat it (its usually reserved for modules needed to be deployed before portal starts).
You should be able to deploy this module on the fly, there are some other tests we use that use this logic, (I believe FileInstall / ServiceBuilder)

**Comment by Kvale1733** [comment]
ci:test:nocompile

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
