### PR TITLE
COMMERCE-7844

### PR DESCRIPTION
**Pull request by LeandroTravassos**
https://issues.liferay.com/browse/COMMERCE-7844

### CODE REVIEW

**Comment by LeandroTravassos** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
Discusses changes with @LeandroTravassos

**Comment by LeandroTravassos** [comment]
Changes have been made

**Comment by LeandroTravassos** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
