### PR TITLE
COMMERCE-8279 | Master

### PR DESCRIPTION
**Pull request by bronsonsoda**
https://issues.liferay.com/browse/COMMERCE-8279

### CODE REVIEW

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
Discussed changes with @bronsonsoda

**Comment by nikki-pru** [comment]
@bronsonsoda , Chao sent in some changes that might be helpful for this test. See https://github.com/nikki-pru/liferay-portal/pull/169

**Comment by bronsonsoda** [comment]
ci:test:sf

**Pull request closed without merging**
