### PR TITLE
COMMERCE-7843-II | master

### PR DESCRIPTION
**Pull request by LeandroTravassos**
https://issues.liferay.com/browse/COMMERCE-7843

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
Discussed changes with @LeandroTravassos

**Comment by LeandroTravassos** [comment]
ci:test:sf

**Comment by LeandroTravassos** [comment]
Changes discussed with @Kvale1733 are done.

**Comment by Kvale1733** [comment]
Pushed to NPrudencio

https://github.com/nikki-pru/liferay-portal/pull/157

**Comment by Kvale1733** [comment]
ci:close

**Comment by Kvale1733** [comment]
Closing PR as it's been merged.

**Pull request closed without merging**
