### PR TITLE
COMMERCE 9377, COMMERCE 9378, COMMERCE 9379, COMMERCE 9380, COMMERCE 9381 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/COMMERCE-9377
https://issues.liferay.com/browse/COMMERCE-9378
https://issues.liferay.com/browse/COMMERCE-9379
https://issues.liferay.com/browse/COMMERCE-9380
https://issues.liferay.com/browse/COMMERCE-9381

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
Testing here: https://github.com/Kvale1733/liferay-portal/pull/112

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
