### PR TITLE
COMMERCE-7680, COMMERCE-7681, COMMERCE-7683 | master

### PR DESCRIPTION
**Pull request by alessandromalves**
https://issues.liferay.com/browse/COMMERCE-7680
https://issues.liferay.com/browse/COMMERCE-7681
https://issues.liferay.com/browse/COMMERCE-7683

### CODE REVIEW

**Comment by alessandromalves** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
Discusses changes with @alessandromalves

**Comment by alessandromalves** [comment]
ci:test:sf

**Comment by alessandromalves** [comment]
ci:test:sf

**Comment by alessandromalves** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
Rebased and resent here: https://github.com/Kvale1733/liferay-portal/pull/81

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
